### PR TITLE
fix(expo, ios)!: iosUserTrackingPermission no longer added by default in Expo

### LINKED ISSUE #272: NSUserTrackingUsageDescription included by default on Expo
## 🐛 Bug Report
`react-native-fbsdk-next` is including `NSUserTrackingUsageDescription` by default in `infoPlist`.

## To Reproduce
Just install this library as dependency in your Expo project, and you'll see `NSUserTrackingUsageDescription` added by default in your `infoPlist` file, after building with `eas build`.

## Expected Behavior
Not to be included by default (in the `infoPlist` file)

### PR DESCRIPTION
**Pull request by foloinfo**
Fixes #272

Test Plan: `yarn test`

Please give any feedback whether it is better to have default `NSUserTrackingUsageDescription` or make it optional.

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
looks good to me, and, actually looks backwards compatible, if previous users were using `false` to avoid the permission, they will still avoid the permission...

**Comment by mikehardy** [comment]
Not sure how this passed your builds locally while you were testing this - you were testing it locally pre-submission right?

Appears to fail during initial build with type errors

```

ℹ Generating type definitions with tsc
plugin/src/__tests__/withUserTrackingPermission-test.ts:8:10 - error TS2322: Type 'boolean' is not assignable to type 'string'.
8         {iosUserTrackingPermission: false},
         ~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in plugin/src/__tests__/withUserTrackingPermission-test.ts:8
✖ Failed to build definition files.
bob build
```

**Comment by foloinfo** [comment]
Oops! I only run `yarn test locally, I'take a look.

**Comment by foloinfo** [comment]
It was failing with `yarn validate:ts` (I'm not used to ts), I checked with `npm run clean:plugin && npm run build:plugin` and it seems like working, so I hope it passes now.

I also realized if I removed bool type from `string | bool`, then the current user might be forced to change their settings (which will do nothing), so I kept the interface same, rather than removing it.

@mikehardy Could you re-check the changes?

**Review by mikehardy — APPROVED** [review]
LGTM

**Comment by mikehardy** [comment]
I merged it as a breaking change with as clear a message as I could think of telling who was affected and who could ignore, and if affected what exactly it is. Those never bother me as a developer, so, should be good to go

**Pull request merged**
