### PR TITLE
fix(android): Profile.getCurrentProfile() always returns null in the firs…

### LINKED ISSUE #258: [Android] Profile.getCurrentProfile() always returns null in the first time
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-fbsdk-next@8.0.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java b/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
index dc4fc02..4f445e6 100644
--- a/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
+++ b/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
@@ -1,6 +1,7 @@
 package com.facebook.reactnative.androidsdk;
 
 import com.facebook.Profile;
+import com.facebook.ProfileTracker;
 import com.facebook.react.bridge.Callback;
 import com.facebook.react.bridge.NativeModule;
 import com.facebook.react.bridge.ReactContextBaseJavaModule;
@@ -11,31 +12,42 @@ import com.facebook.react.module.annotations.ReactModule;
 import androidx.annotation.NonNull;
 
 /**
- * This is a {@link NativeModule} that allows JS to use FBSDKProfile info of the current logged user.
+ * This is a {@link NativeModule} that allows JS to use FBSDKProfile info of the
+ * current logged user.
  */
 @ReactModule(name = FBProfileModule.NAME)
 public class FBProfileModule extends ReactContextBaseJavaModule {
-    public static final String NAME = "FBProfile";
+  public static final String NAME = "FBProfile";
+  private ProfileTracker mProfileTracker;
 
-    public FBProfileModule(ReactApplicationContext reactContext) {
-      super(reactContext);
-    }
+  public FBProfileModule(ReactApplicationContext reactContext) {
+    super(reactContext);
+  }
 
-    @NonNull
-    @Override
-    public String getName() {
+  @NonNull
+  @Override
+  public String getName() {
     return NAME;
   }
 
-    /**
-    * Get the current logged profile.
-    * @param callback Use callback to pass the current logged profile back to JS.
-    */
-    @ReactMethod
-    public void getCurrentProfile(Callback callback) {
-        //Return the profile object as a ReactMap.
-        callback.invoke(Profile.getCurrentProfile() == null
-                ? null
-                : Utility.profileToReactMap(Profile.getCurrentProfile()));
+  /**
+   * Get the current logged profile.
+   * 
+   * @param callback Use callback to pass the current logged profile back to JS.
+   */
+  @ReactMethod
+  public void getCurrentProfile(final Callback callback) {
+    // Return the profile object as a ReactMap.
+    if (Profile.getCurrentProfile() == null) {
+      mProfileTracker = new ProfileTracker() {
+        @Override
+        protected void onCurrentProfileChanged(Profile oldProfile, Profile currentProfile) {
+          callback.invoke(Utility.profileToReactMap(currentProfile));
+          mProfileTracker.stopTracking();
+        }
+      };
+    } else {
+      callback.invoke(Utility.profileToReactMap(Profile.getCurrentProfile()));
+    }
   }
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by hiepnsx**
Fixes #258 #73

### CODE REVIEW

**Comment by hiepnsx** [comment]
@mikehardy Can you check this PR?

**Review by mikehardy — COMMENTED** [review]
Okay I think I reviewed something like this code before? I feel like I have the same concern, it seems to me this could leave an unresolved promise forever if the listener is never called. I feel like there should be some link to documentation that indicates it will always be called and within what timeframe, or there should be a timer that will eventually resolve and allow it to return. I've worked on other libraries that occasionally left unresolved promises and I assure if this is nit handled and I merge it I'll be tagging you on a bug report for unresolved promises just a week or so from now...

**Comment by hiepnsx** [comment]
@mikehardy Thank you for taking time.
> Okay I think I reviewed something like this code before?
I think so, because this is a "popular" solution I get from stackoverflow.
I understand your concern. What do you think about this?
https://github.com/thebergamo/react-native-fbsdk-next/compare/f556df5ec0db1516e1d54f18f075884a0a5c8bfa..f754256b659bfb848b1ba9933dd52a6b309258a9
I haven't tested it yet, but if you think it's good enough, I will test it in my project.

**Comment by mikehardy** [comment]
Looks about right but cancel the timer before invoke in listener and synchronize on timer object to close off all multi thread double promise resolution possibilities i think? This could merge though

**Comment by hiepnsx** [comment]
@mikehardy I have updated PR. Please check it again.

**Review by mikehardy — APPROVED** [review]
This seems fine to me - thanks for taking the time to propose a PR, and to work with me to (hopefully!) make it really robust. We'll see how it goes when it goes out in the wild :-)

**Pull request merged**
