### PR TITLE
fix(android): ShareDialog.setMode('native') throws in Turkish language

### LINKED ISSUE #239: No enum constant com.facebook.share.widget.ShareDialog.Mode.NATİVE
## 🐛 Bug Report
```ts
ShareDialog.setMode('native')
```

When the phone language is set to `Azerbaijani` or `Turkish` the above line causes following exception:
```bash
Fatal Exception: java.lang.IllegalArgumentException: NATİVE is not a constant in com.facebook.share.widget.ShareDialog$Mode
       at java.lang.Enum.valueOf(Enum.java:200)
       at com.facebook.share.widget.ShareDialog$Mode.valueOf(ShareDialog.java:73)
       at com.facebook.reactnative.androidsdk.FBShareDialogModule.setMode(FBShareDialogModule.java:99)
```

## To Reproduce
- Set the interface language to Azerbaijani or Turkish
- Call `ShareDialog.setMode('native')`

## Cause
The reason for this error is that in those languages `"native".toUpperCase()` call returns `NATİVE` not `NATIVE` (note that the dotted and dotless capital `i`).

https://github.com/thebergamo/react-native-fbsdk-next/blob/caf9c0a5e3f3eaf267a1b817c73c83fc98b67d66/android/src/main/java/com/facebook/reactnative/androidsdk/FBShareDialogModule.java#L99

## Workaround
Pass dialog mode in capital letters
```ts
ShareDialog.setMode('NATIVE')
```

## Fix
Fix would be passing `Locale.ENGLISH` to uppercase function:
```patch
-mShareDialogMode = ShareDialog.Mode.valueOf(mode.toUpperCase());
+import java.util.Locale;
+mShareDialogMode = ShareDialog.Mode.valueOf(mode.toUpperCase(Locale.ENGLISH));
```

### PR DESCRIPTION
**Pull request by OrkhanAlikhanov**
Fixes #239 

Test Plan:
I don't think it needs a test case, but I can provide one if necessary

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]

**Comment by mikehardy** [comment]
Oh no hahah - there are a lot of them!

```
src/main/java/com/facebook/reactnative/androidsdk/FBShareDialogModule.java:        mShareDialogMode = ShareDialog.Mode.valueOf(mode.toUpperCase());
src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:            behavior = LoginBehavior.valueOf(loginBehavior.toUpperCase());
src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:            audience = DefaultAudience.valueOf(defaultAudience.toUpperCase());
src/main/java/com/facebook/reactnative/androidsdk/Utility.java:                    GameRequestContent.ActionType.valueOf(actionType.toUpperCase()));
src/main/java/com/facebook/reactnative/androidsdk/Utility.java:                    GameRequestContent.Filters.valueOf(filters.toUpperCase()));
src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java:        LoginBehavior loginBehavior = LoginBehavior.valueOf(loginBehaviorString.toUpperCase());
src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java:        DefaultAudience defaultAudience = DefaultAudience.valueOf(defaultAudienceString.toUpperCase());
src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:        AppEventsLogger.setFlushBehavior(AppEventsLogger.FlushBehavior.valueOf(flushBehavior.toUpperCase(Locale.ROOT)));
src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:                AppEventsLogger.ProductAvailability.valueOf(availability.toUpperCase(Locale.ROOT)),
src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:                AppEventsLogger.ProductCondition.valueOf(condition.toUpperCase(Locale.ROOT)),

```

This only fixes 1 of the remaining 7, do you have this checked out locally in order to change the rest or were you just using the web UI? I can change the rest if you don't actually have it checked out etc

**Comment by mikehardy** [comment]
some toLowerCase also

```
src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java:        promise.resolve(LoginManager.getInstance().getLoginBehavior().name().toLowerCase());
src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java:        promise.resolve(LoginManager.getInstance().getDefaultAudience().name().toLowerCase());

```

**Comment by OrkhanAlikhanov** [comment]
Haha I was also going to report those. Good job!

**Comment by OrkhanAlikhanov** [comment]
>This only fixes 1 of the remaining 7, do you have this checked out locally in order to change the rest or were you just using the web UI? I can change the rest if you don't actually have it checked out etc

I only used web UI. Would be great if you did those.

**Comment by mikehardy** [comment]
Okay - I'll pull your PR locally and patch up the rest then we can fix this :-). Thanks for noticing it! The fix is easy - noticing it is clearly the hard part.

**Review by mikehardy — APPROVED** [review]
got them all now!

**Pull request merged**
