### PR TITLE
chore(test): add testID optional type to login button for use in testing

### PR DESCRIPTION
**Pull request by doublethefish**
Test Plan:
The commit itself adds a test to demonstrate a usecase.

### CODE REVIEW

**Comment by doublethefish** [comment]
I am not sure why the `PR Title is Conventional` check fails with:

> No release type found in pull request title "chore(test) Adds type-hint for testID for downstream testing". Add a prefix to indicate what kind of release this pull request corresponds to

Happy to change it to something that passes.

**Comment by mikehardy** [comment]
conventional commits mandates a colon separating the type and the message - that's the issue I think https://www.conventionalcommits.org/en/v1.0.0/

**Review by mikehardy — APPROVED** [review]
Cool - this change looks obviously good to me, I'll change the PR title but I think the checker will still fail (mostly as a warning now, for maintainers) since GitHub will by default take the commit message on single commits, but if I squash merge I can make sure it's right (in other words: no action required to make it conventional)

**Comment by mikehardy** [comment]
CI passed, and I just re-read it again to make sure it still looked good to me just in case, I think this is good to go, thanks again!

**Comment by mikehardy** [comment]
Note that I actually merged it as a feature - when I was considering it, this is actually a new feature for the library (even if it is only for use in testing downstream) and it won't generate a release of the right type unless committed as such.

**Comment by doublethefish** [comment]
Grand, thank you.

**Pull request merged**
