### PR TITLE
feat(Expo): bump Expo Adapters version from 13.0 to 13.4

### PR DESCRIPTION
**Pull request by mihailapuste**
Bumped iOS deployment target to 13.4 to support expo sdk 50

### CODE REVIEW

**Comment by mikehardy** [comment]
I am unsure why supporting a new version of Expo requires a breaking change in the expo adapters for all expo users? 🤔

**Comment by mihailapuste** [comment]
@mikehardy Sorry for the late reply! 
That absolutely makes sense, no reason to merge with breaking changes for now. I've personally forked for my own needs.
However I thought of perhaps leaving his here, perhaps it will be needed, and if not, please feel free to close.

Expo 50 now has a minimum deployment target of `13.4`

> [Notable breaking changes](https://expo.dev/changelog/2024/01-18-sdk-50#notable-breaking-changes)
> iOS minimum deployment target bumped to 13.4.

**Comment by mikehardy** [comment]
There are easier ways I think? I do something like this to line up my targets, in my `Podfile`

```ruby
post_install do |installer|

min_ios_version_supported = '13.4'

  # ...lots of stuff

  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|

      # Quiets all the noise about misaligned deployment targets
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
    end
  end

  # ...anything else you might need

end

```

**Comment by mihailapuste** [comment]
> There are easier ways I think? I do something like this to line up my targets, in my `Podfile`
> 
> ```ruby
> min_ios_version_supported = '13.4'
> 
> 
> post_install do |installer|
> 
>   # ...lots of stuff
> 
>   installer.pods_project.targets.each do |target|
> 
>     target.build_configurations.each do |config|
> 
>       # Quiets all the noise about misaligned deployment targets
>       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
>     end
>   end
> 
>   # ...anything else you might need
> 
> end
> ```

This seems to have done the trick. Thank you for your help 🚀 @mikehardy

**Pull request closed without merging**
