### PR TITLE
fix(expo): bump expo dependency

### LINKED ISSUE #309: Expo 46 config-plugins version incompatibility
## 🐛 Bug Report

Expo config has had a major release and as of expo sdk 46 is now at 5.x.x. 
The expo config version this package uses is locked at 4.x.x which makes builds with expo 46 log warnings about invalid @expo/config-plugins.
```yarn why @expo/config-plugins``` returns this:
```
info Has been hoisted to "@expo/config-plugins"
info Reasons this module exists
   - Hoisted from "expo-dev-client#@expo#config-plugins"
   - Hoisted from "expo-notifications#@expo#config-plugins"
   - Hoisted from "expo-system-ui#@expo#config-plugins"
   - Hoisted from "expo-tracking-transparency#@expo#config-plugins"
   - Hoisted from "sentry-expo#@expo#config-plugins"
   - Hoisted from "expo-updates#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-launcher#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-menu#@expo#config-plugins"
   - Hoisted from "expo#expo-file-system#@expo#config-plugins"
   - Hoisted from "expo#@expo#cli#@expo#config-plugins"
   - Hoisted from "expo-constants#@expo#config#@expo#config-plugins"
   - Hoisted from "expo-splash-screen#@expo#prebuild-config#@expo#config-plugins"
info Disk size without dependencies: "1.92MB"
info Disk size with unique dependencies: "3.32MB"
info Disk size with transitive dependencies: "6.84MB"
info Number of shared dependencies: 47
=> Found "react-native-fbsdk-next#@expo/config-plugins@4.1.5"
info This module exists because "react-native-fbsdk-next" depends on it.
info Disk size without dependencies: "1.57MB"
info Disk size with unique dependencies: "2.97MB"
info Disk size with transitive dependencies: "6.5MB"
info Number of shared dependencies: 47
```

## To Reproduce

Use react-native-fbsdk-next with expo 46

## Expected Behavior

expo doctor config-plugin check passes. Unlike now, which fails as below:
```
Running "expo doctor"
- Finding all copies of expo-modules-autolinking
- Finding all copies of @expo/config-plugins
[stderr] [07:39:36] Expected package @expo/config-plugins@^*.0.0
[stderr] [07:39:36] Found invalid:
[stderr] [07:39:36]   @expo/config-plugins@4.1.*
[stderr] [07:39:36]   (for more info, run: npm why @expo/config-plugins)
- Finding all copies of @expo/prebuild-config
- Finding all copies of @unimodules/core
- Finding all copies of @unimodules/react-native-adapter
- Finding all copies of react-native-unimodules
Command "expo doctor" failed.bash exited with non-zero code: 1
```

## Environment

"react-native": "0.69.5",
"react-native-fbsdk-next": "^10.1.0",
"expo": "~46.0.9",

### PR DESCRIPTION
**Pull request by stdavis**
This will bring make this library more compatible with the latest expo SDK release

Fixes #309

Test Plan:

`yarn test`

Thanks for the awesome library!

### CODE REVIEW

**Comment by stdavis** [comment]
Just realized that this is a duplicate of #327. If you would be willing to approve running the workflows in this PR, I'd be happy to take a look at getting CI to all green. Thanks!

**Comment by mikehardy** [comment]
CI is running now :-)

**Review by mikehardy — APPROVED** [review]
💥

**Comment by mikehardy** [comment]
Nope - just working through morning notifications and such and got the end of the queue where your ping's notification landed. Merged + releasing now, thanks for the help!

**Pull request merged**
