### PR TITLE
feat(ios, sdk): upgrade to FBSDK version 9.3.x

### PR DESCRIPTION
**Pull request by bcomeau**
Fix issue #44

### CODE REVIEW

**Comment by mikehardy** [comment]
Seems fine - is there anything similar required for android to get it current https://github.com/facebook/facebook-android-sdk/releases (9.1.1)  vs current default of 9.0.x https://github.com/thebergamo/react-native-fbsdk-next/blob/73e3803b576ca6240ab6cee69a7f0e2447444979/android/build.gradle#L48

**Review by mikehardy — APPROVED** [review]
LGTM - I made the PR title "conventional" (Angular conventional commits format) and approved the CI run

**Comment by bcomeau** [comment]
> Seems fine - is there anything similar required for android to get it current https://github.com/facebook/facebook-android-sdk/releases (9.1.1) vs current default of 9.0.x
> 
> https://github.com/thebergamo/react-native-fbsdk-next/blob/73e3803b576ca6240ab6cee69a7f0e2447444979/android/build.gradle#L48

Maybe changing
`def FACEBOOK_SDK_VERSION = safeExtGet('facebookSdkVersion', '9.0.+') `
to
`def FACEBOOK_SDK_VERSION = safeExtGet('facebookSdkVersion', '9.3.+') `

And then run the CI 🤞

**Comment by mikehardy** [comment]
9.1.1 is current for android, so 9.3 would not fly :)

CI on this change failed

```

[!] CocoaPods could not find compatible versions for pod "FBSDKShareKit":
  In snapshot (Podfile.lock):
    FBSDKShareKit (= 9.0.1, ~> 9.0.1)

  In Podfile:
    react-native-fbsdk-next (from `../../`) was resolved to 4.2.0, which depends on
      react-native-fbsdk-next/Share (= 4.2.0) was resolved to 4.2.0, which depends on
        FBSDKShareKit (~> 9.3)
```

You need to update Podfile.lock on the example as well, but that's tedious, the example should just delete Podfile.lock before running

If you edited this line:

https://github.com/thebergamo/react-native-fbsdk-next/blob/73e3803b576ca6240ab6cee69a7f0e2447444979/.github/workflows/ci.yml#L79

To be this command `cd example/ios && rm -f Podfile.lock && pod install` vs the existing one, it should work

**Comment by thebergamo** [comment]
Lgtm as well 😬

**Pull request merged**
