### PR TITLE
feat(expo): upgrade expo config plugin to v51

### PR DESCRIPTION
**Pull request by LukeGu-web**
Upgrade expo to the latest version (v51.0.38) and dependencies to match the SDK version.

Update Facebook-related configuration.

### CODE REVIEW

**Comment by mikehardy** [comment]
@LukeGu-web you are a champion! Thanks for working through some of this technical debt, I really appreciate it
Check the details link on the ios/android CI runs - this is why I haven't done this one yet, I took a quick look at it (bumping the deps like you did) and immediately had some typing errors

Now, they may not be too hard to fix? They shouldn't be? But I simply had no time when I tried it. Hopefully they are not too difficult to sort out, I'd love to get the dependencies up to date

Cheers

**Comment by LukeGu-web** [comment]
> @LukeGu-web you are a champion! Thanks for working through some of this technical debt, I really appreciate it Check the details link on the ios/android CI runs - this is why I haven't done this one yet, I took a quick look at it (bumping the deps like you did) and immediately had some typing errors
> 
> Now, they may not be too hard to fix? They shouldn't be? But I simply had no time when I tried it. Hopefully they are not too difficult to sort out, I'd love to get the dependencies up to date
> 
> Cheers

In Expo v51, the Facebook-related configuration properties have been moved and restructured.

I updated the config type and it can be installed and built locally. Hope I haven't broken anything accidentally. 🤞

**Review by mikehardy — APPROVED** [review]
Hey @LukeGu-web - thanks for your patience. This all seems fine, just to double-check, nothing needs to change in the documentation here? if so, happy to merge and release

**Comment by LukeGu-web** [comment]
> Hey @LukeGu-web - thanks for your patience. This all seems fine, just to double-check, nothing needs to change in the documentation here? if so, happy to merge and release

Sorry Mike, I just saw this message. The document doesn't need to be modified. I just made the config type meet the new structure.

**Pull request merged**
